FROM golang:1.24-alpine AS builder

ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apk add --no-cache \
    make \
    nodejs \
    npm \
    inotify-tools \
    bash

# Create and change to non-root user
RUN addgroup -g $USER_GID devrunner \
    && adduser -G devrunner -u $USER_UID -D devrunner

# Change to non-root user and enter home directory
USER devrunner
WORKDIR /home/devrunner

# Install development tools
RUN go install github.com/air-verse/air@latest \
    && go install github.com/a-h/templ/cmd/templ@latest

COPY --chown=devrunner:devrunner ./scripts/docker-run.sh ./

# Use npm to install dependencies
COPY --chown=devrunner:devrunner package.json package-lock.json ./
RUN npm install

# Install go project dependencies
COPY --chown=devrunner:devrunner go.mod go.sum ./
RUN go mod download

# Create and enter src folder
RUN mkdir /home/devrunner/src
WORKDIR /home/devrunner/src
VOLUME /home/devrunner/src

# Expose the web server
EXPOSE 8080

# Expose the live reload web socket
EXPOSE 8010

ENTRYPOINT ["/home/devrunner/docker-run.sh"]

