networks:
  http_network:
    external: true
  store_network:
    external: false

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - type: bind
        source: ./db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
        read_only: true
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - store_network
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  webserver:
    image: "elbromasmc/team-support"
    restart: unless-stopped
    volumes:
      - store-images:/images
    environment:
      - ENV=${ENV}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SESSION_KEY=${SESSION_KEY}
      - PORT=${PORT}
      - REL=${REL}
      - SMTP_HOSTNAME=${SMTP_HOSTNAME}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - WEBSERVER_HOSTNAME=${WEBSERVER_HOSTNAME}
      - IZIPAY_STOREID=${IZIPAY_STOREID}
      - IZIPAY_APIKEY=${IZIPAY_APIKEY}
      - COMPANY_EMAIL=${COMPANY_EMAIL}
      - BOOK_EMAIL=${BOOK_EMAIL}
    networks:
      - http_network
      - store_network
    labels:
      - "traefik.enable=true"
      # Middleware
      - "traefik.http.middlewares.redirect-non-www-to-www.redirectregex.permanent=true"
      - "traefik.http.middlewares.redirect-non-www-to-www.redirectregex.regex=^https://teamsupportperu.com/(.*)"
      - "traefik.http.middlewares.redirect-non-www-to-www.redirectregex.replacement=https://${WEBSERVER_HOSTNAME}/$${1}"
      # The application
      - "traefik.docker.network=http_network"
      - "traefik.http.routers.webserver.entrypoints=websecure"
      - "traefik.http.routers.webserver.rule=Host(`${WEBSERVER_HOSTNAME}`) || Host(`teamsupportperu.com`)"
      - "traefik.http.routers.webserver.middlewares=redirect-non-www-to-www"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.tls.certresolver=letsencrypt"
      - "traefik.http.routers.webserver.tls.domains[0].main=${WEBSERVER_HOSTNAME}"
      - "traefik.http.routers.webserver.tls.domains[0].sans=teamsupportperu.com"
      - "traefik.http.routers.webserver.tls.options=default"
      - "traefik.http.services.webserver.loadbalancer.server.port=8080"
      - "traefik.http.services.webserver.loadbalancer.server.scheme=http"
    depends_on:
      db:
        condition: service_healthy
volumes:
  db-data:
  store-images:

