version: "3"

dotenv:
  - .env
  - .env.local

tasks:
  dev:
    run: always
    cmds:
      - air

  build:
    aliases:
      - gen
      - g
    cmds:
      - npm run dev
      - templ generate -path ./view
      - go build -o ./tmp/main cmd/main.go
