// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"alc/view/layout"
)

func Ticket() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main><section class=\"relative h-[calc(100dvh-4rem)]\"><img class=\"relative object-cover w-full h-full\" src=\"/static/img/ticket.jpg\" alt=\"\"><div class=\"absolute inset-0 flex justify-center items-center px-4\"><div class=\"text-chalky\"><h2 class=\"mb-8 text-center text-3xl font-semibold lg:mb-16 lg:text-5xl\">Consulta tu ticket</h2><div class=\"flex flex-col items-center gap-6 font-bold lg:flex-row lg:gap-16\"><a class=\"px-9 py-2 rounded-2xl bg-azure\" href=\"http://www.teamsupportperu.com/compu_data_client/consulta_ot.aspx\">Cliente</a> <a class=\"px-9 py-2 rounded-2xl bg-azure\" href=\"http://www.teamsupportperu.com/compu_data_client/login.aspx\">Cliente corporativo</a> <a class=\"px-9 py-2 rounded-2xl bg-azure\" href=\"http://www.teamsupportperu.com/compu_data/inicio_rep.aspx\">Fabricante</a> <a class=\"px-9 py-2 rounded-2xl bg-azure\" href=\"http://www.teamsupportperu.com/compu_data/marca.aspx\">Intranet</a></div></div></div></section></main>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.BasePage("Consultar ticket").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
